## Aknur Mansurkhan

### Topic: RNN (recurrent neural networks)

leccture practice tasks

3.1.

 Берілген уақыттық қатар:

 [2, 4, 6, 8, 10]

 RNN көмегімен келесі мәнді болжау идеясының логикасын түсіндір.

In [8]:
import numpy as np

In [9]:
def simple_rnn(sequence):
    h = 0

    for x in sequence:
        h = h + (x - h) * 0.5  # Өткенді есте сақтау
        print(f"Кіріс: {x}, Жасырын күй: {h:.1f}")

    difference = sequence[-1] - sequence[-2]
    prediction = sequence[-1] + difference

    return prediction

In [10]:
sequence = [2, 4, 6, 8, 10]
result = simple_rnn(sequence)

print(f"Болжам: {result}")

Кіріс: 2, Жасырын күй: 1.0
Кіріс: 4, Жасырын күй: 2.5
Кіріс: 6, Жасырын күй: 4.2
Кіріс: 8, Жасырын күй: 6.1
Кіріс: 10, Жасырын күй: 8.1
Болжам: 12



3.2.

 Мәтіндік деректер үшін RNN қолданғанда:

input қалай беріледі?

one-hot encoding не үшін керек?


________________________________

1. Input Қалай Беріледі?

Мысал мәтін:

"hello"
Қадам 1: Токенизация (Сөздерге бөлу)

    ['h', 'e', 'l', 'l', 'o']

Қадам 2: Сөздікке айналдыру

Сөздік:

    'h' → 0

    'e' → 1

    'l' → 2

    'o' → 3

Қадам 3: Сандарға түрлендіру

"hello" → [0, 1, 2, 2, 3]

Қадам 4: RNN-ге беру

     x₁=0    x₂=1    x₃=2    x₄=2    x₅=3
      ↓       ↓       ↓       ↓       ↓
    [RNN] → [RNN] → [RNN] → [RNN] → [RNN]

Әр уақыт қадамында: бір әріп (немесе сөз) беріледі

_________________

Неге One-Hot Керек?

1. Математикалық қатынасты алып тастайды

        Жаман:  'a'=0, 'z'=25  →  'z' > 'a' ❌

        Жақсы:  'a'=[1,0,...], 'z'=[0,...,1]  →  теңдей ✅

2. Нейрондық желі түсінеді

        One-hot вектор = желі үшін түсінікті формат

3. Әр әріп бірегей

        'h' ≠ 'e' ≠ 'l' ≠ 'o'  (барлығы ерекше)

In [11]:
import numpy as np


text = "hello"


chars = sorted(set(text))
char_to_idx = {ch: i for i, ch in enumerate(chars)}

print("Сөздік:", char_to_idx)
# {'e': 0, 'h': 1, 'l': 2, 'o': 3}

#  Сандарға түрлендіру
indices = [char_to_idx[ch] for ch in text]
print("Индекстер:", indices)
# [1, 0, 2, 2, 3]

# One-hot encoding
vocab_size = len(chars)
one_hot = np.zeros((len(text), vocab_size))

for i, idx in enumerate(indices):
    one_hot[i, idx] = 1

print("\nOne-hot vectors:")
print(one_hot)

Сөздік: {'e': 0, 'h': 1, 'l': 2, 'o': 3}
Индекстер: [1, 0, 2, 2, 3]

One-hot vectors:
[[0. 1. 0. 0.]
 [1. 0. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]



3.3.

 LSTM қолдану қажет болатын нақты 3 жағдай ойлап тап және түсіндір.

Python тілінде keras кітапханасын қолданып, бір қабатты RNN моделін құр.


1. Машина Аударма (Machine Translation)
Мәселе:

Қазақша: "Мен бүгін университетке бардым"

Ағылшынша: "I went to university today"Неге LSTM керек:

Сөйлем басындағы "Мен" соңындағы "бардым" етістігімен байланысты

Ұзақ тәуелділік: бірінші сөз соңғы сөзге әсер етеді

Қарапайым RNN: ұзын сөйлемде басын ұмытады

LSTM: бастан соңына дейін контексті сақтайды

      Мен → бүгін → университетке → бардым
      ↓      ↓          ↓            ↓
      I  → today →     to      → university → went
                                        ↑____________|
                              (LSTM есте сақтайды)

2. Акциялар Бағасын Болжау (Stock Price Prediction)

Мәселе:

Бір жыл бұрынғы оқиға (мысалы, пандемия) бүгінгі бағаға әсер етуі мүмкін

Неге LSTM керек:

    Ұзақ мерзімді жады: 6 ай бұрынғы үрдісті есте сақтау

    Маусымдық үлгілер: қыста бағалар өседі, жазда түседі

    Қарапайым RNN: тек соңғы 10-20 күнді есте сақтайды

    LSTM: жылдық тренд пен апталық өзгерістерді бірге ескереді

--------------------------

    2023 жаз (↓) → 2023 күз (↑) → 2024 қыс (↑↑) → 2024 көктем (?)
        ↓              ↓              ↓              ↓
      LSTM барлық тарихты есте сақтап, болжам жасайды

3. Медициналық Диагностика (Medical Diagnosis)

Мәселе:

Науқастың бүкіл медициналық тарихы маңызды:

- 5 жыл бұрын: жүрек ауруы
- 2 жыл бұрын: диабет
- Қазір: жоғары қан қысымы

Диагноз: барлық тарихты ескеру керек!

Неге LSTM керек:

    Ұзақ мерзімді науқас тарихы: 10 жыл бұрынғы науқаслық маңызды
    Себеп-салдар байланысы: бұрынғы аурулар қазіргіге әсер етеді
    Қарапайым RNN: тек соңғы 3-5 визитті есте сақтайды
    LSTM: толық медициналық профильді сақтайды

____________


    2018: операция → 2020: аллергия → 2023: жүрек ауруы → 2025: ???
            ↓              ↓                ↓               ↓
        LSTM барлық тарихты талдап, дұрыс диагноз қояды

In [20]:
import numpy as np
from keras.models import Sequential
from keras.layers import SimpleRNN, Dense
from keras.utils import to_categorical

In [21]:
# 1. ДЕРЕК ДАЙЫНДАУ
text = "hello"
chars = sorted(set(text))
char_to_idx = {ch: i for i, ch in enumerate(chars)}
idx_to_char = {i: ch for ch, i in char_to_idx.items()}

vocab_size = len(chars)
print(f"Сөздік: {char_to_idx}")
print(f"Өлшем: {vocab_size}")


Сөздік: {'e': 0, 'h': 1, 'l': 2, 'o': 3}
Өлшем: 4


In [22]:
# Input: "hell" → Output: "o"
sequence = [char_to_idx[ch] for ch in text]
X = []
y = []

In [23]:
# Әр 4 әріптен келесі әріпті болжаймыз
seq_length = 4
for i in range(len(sequence) - seq_length):
    X.append(sequence[i:i+seq_length])
    y.append(sequence[i+seq_length])

X = np.array(X)
y = np.array(y)

print(f"X shape: {X.shape}")
print(f"y shape: {y.shape}")
print(f"X: {X}")  # [[0 1 2 2]] → "hell"
print(f"y: {y}")  # [3] → "o"

X shape: (1, 4)
y shape: (1,)
X: [[1 0 2 2]]
y: [3]


In [24]:
# ONE-HOT ENCODING
X = to_categorical(X, num_classes=vocab_size)
y = to_categorical(y, num_classes=vocab_size)

print(f"X one-hot shape: {X.shape}")
print(f"y one-hot shape: {y.shape}")

X one-hot shape: (1, 4, 4)
y one-hot shape: (1, 4)


In [25]:
model = Sequential([
    SimpleRNN(units=50,
              activation='relu',
              input_shape=(seq_length, vocab_size)),  # (4, 4)
    Dense(vocab_size, activation='softmax')
])

In [26]:
model.compile(
    optimizer='adam',
    loss='categorical_crossentropy',
    metrics=['accuracy']
)


In [27]:
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn_1 (SimpleRNN)        │ (None, 50)             │         2,750 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 4)              │           204 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2,954 (11.54 KB)

 Trainable params: 2,954 (11.54 KB)

 Non-trainable params: 0 (0.00 B)

In [28]:
history = model.fit(
    X, y,
    epochs=500,
    verbose=0  # Тек соңғы нәтижені көрсет
)

print(f"Соңғы accuracy: {history.history['accuracy'][-1]:.2%}")
print(f"Соңғы loss: {history.history['loss'][-1]:.4f}")


Соңғы accuracy: 100.00%
Соңғы loss: 0.0000


In [29]:
test_input = X[0].reshape(1, seq_length, vocab_size)
prediction = model.predict(test_input, verbose=0)
predicted_idx = np.argmax(prediction)
predicted_char = idx_to_char[predicted_idx]

print(f"Input: 'hell'")
print(f"Predicted: '{predicted_char}'")

Input: 'hell'
Predicted: 'o'
