Aknur Mansukhan


> Теориялык тапсырмалар (Ойлауга арналган)


---


1. BoW vs TF-IDF: Неліктен "жэне", "бірак", "сол" сиякты жиі кездесетін сездер Bag of Words дісінде мэселе тудыруы мумкін? TF-IDF бул мэселені калай шешеді?


---



BoW тек сөздің қанша рет кездескенін санайды

Мысал:

    I love data science  
    I love pizza

BoW үшін ең маңызды сөз → I

Бірақ бұл пайдалы сөз емес

Себебі:

    жиі кездесетін сөздер:
    the / and / is / және / мен

мәтіннің мағынасын бермейді


TF-IDF:

жиі кездесетін сөздерге салмақ ↓

сирек маңызды сөздерге салмақ ↑

Мысалы:

    "machine", "pizza" → маңызды
    "I", "is" → маңызды емес

Сондықтан TF-IDF мағыналы сөздерді табады.



---

2. Контекст мэселесі: "Менін басым ауырып тур" жэне "Кітаптын басы кызык екен" деген екі сейлемдегі "бас" сезінін магынасы екі турлі.

 Word2Vec жене BERT модельдерінін кайсысы осы айырмашылыкты жаксырак ажыратады? Неге?


---

Сөйлемдер:

    Менің басым ауырып тұр → дене мүшесі
    Кітаптың басы қызық → басталуы

Word2Vec

    Бір сөзге → бір ғана вектор береді ❌
    Контекстті түсінбейді

BERT

    Бір сөзге → әр сөйлемде әртүрлі вектор береді ✅
    Контекстті түсінеді
Дұрыс жауап: BERT жақсырақ



---
3. Cosine Similarity (Косинустық ұқсастық): Егер екі сөздің векторларының арасындағы бұрыш 0° болса, бұл нені білдіреді? Ал 90° болса ше?


---

| Бұрыш | Мағына       |
| ----- | ------------ |
| 0°    | өте ұқсас    |
| 90°   | байланыс жоқ |
| 180°  | қарама-қарсы |





---
4. Tokenization: "Don't" сөзін токенизациялаудың кем дегенде 3 түрлі жолын көрсетіңіз.

Қай әдіс тимдірек деп ойлайсыз?


---

3 вариант:

    ["don't"]
    ["do", "n't"] ✅
    ["don", "'", "t"]

Ең дұрысы → do + n't

Себебі модель терістеуді түсінеді.






> Практикалык тапсырмалар (Код жазуга арналган)
---
А деңгейі: Мәтінді тазалау жэне BoW

Темендегі мәтіндер тізімін алып, барлық еріптерді кішірейтіңіз (lowercase), тыныс белгілерін алып тастаңыз жене оларды CountVectorizer көмегімен санға айналдырыңыз.

---

Орнату

    pip install scikit-learn nltk

In [92]:
data = [
    "Алматы - әдемі қала.",
    "Астана - бас қала!",
    "Алматы мен Астана - үлкен қалалар. "
    ]


In [93]:
import re
from sklearn.feature_extraction.text import CountVectorizer


In [94]:
def clean(text):
    text = text.lower()
    text = re.sub(r'[^\w\s]', '', text) # тыныс белгілерді өшіру
    return text


In [95]:
clean_data = [clean(d) for d in data]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(clean_data)

print("Сөздер:", vectorizer.get_feature_names_out())
print("BoW матрица:\n", X.toarray())

Сөздер: ['алматы' 'астана' 'бас' 'мен' 'қала' 'қалалар' 'үлкен' 'әдемі']
BoW матрица:
 [[1 0 0 0 1 0 0 1]
 [0 1 1 0 1 0 0 0]
 [1 1 0 1 0 1 1 0]]




---


Тапсырма: Осы мәтіндер үшін жиілік матрицасын құрыңыз

В денгейі: TF-IDF қолдану

Sklearn кітапханасын пайдаланып, берілген кұжаттар жиынтығы үшін ең маңызды 3 сөзді
табыңыз (TF-IDF салмағы ең жоғары сөздер)

---



In [96]:
from sklearn.feature_extraction.text import TfidfVectorizer
import numpy as np


In [97]:
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(clean_data)

words = tfidf.get_feature_names_out()
scores = X.toarray().sum(axis=0)

top_ids = np.argsort(scores)[-3:]

print("Ең маңызды 3 сөз:")
for i in top_ids:
    print(words[i])

Ең маңызды 3 сөз:
астана
алматы
қала




---
С деңгейі: HuggingFace-пен жұмыс

transformers

кітапханасын қолданып, келесі екі сөйлемнің, BERT эмбеддингтерін
(векторларын) алаңыз және олардың арасындағы ұқсастықты (similarity) есептеңіз

---




In [98]:
from transformers import AutoTokenizer, AutoModel
import torch
from sklearn.metrics.pairwise import cosine_similarity


In [99]:
sentence1 = "I love machine learning."
sentence2 = "AI is amazing."

In [100]:
tokenizer = AutoTokenizer.from_pretrained("bert-base-uncased")
model = AutoModel.from_pretrained("bert-base-uncased")

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

BertModel LOAD REPORT from: bert-base-uncased
Key                                        | Status     |  | 
-------------------------------------------+------------+--+-
cls.predictions.transform.dense.bias       | UNEXPECTED |  | 
cls.predictions.bias                       | UNEXPECTED |  | 
cls.seq_relationship.weight                | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |  | 
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |  | 
cls.seq_relationship.bias                  | UNEXPECTED |  | 
cls.predictions.transform.dense.weight     | UNEXPECTED |  | 

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.


In [101]:
def get_embedding(text):
    inputs = tokenizer(text, return_tensors="pt")
    outputs = model(**inputs)
    return outputs.last_hidden_state.mean(dim=1).detach().numpy()

In [102]:
emb1 = get_embedding(sentence1)
emb2 = get_embedding(sentence2)

sim = cosine_similarity(emb1, emb2)
print("Ұқсастық:", sim[0][0])

Ұқсастық: 0.78116




---
3️⃣ MINI PROJECT — SPAM FILTER 📧

Сипаттама: Сізде 100 хат бар (бір бөлігі спам, бір бөлігі пайдалы хаттар).

1. Матіндерді TF-IDF аркылы векторга айналдырыныз.
2. LogisticRegression немесе Naive Bayes классификаторын қолданып, хаттың спам
немесе спам емес екенін анықтайтын модель оқытыңыз
---





In [103]:
import pandas as pd
import numpy as np
import re
import nltk




In [104]:
df = pd.read_csv("spam.csv", encoding="latin-1")

df = df[['v1','v2']]
df.columns = ['label','text']

print(df.head())
print(df['label'].value_counts())


  label                                               text
0   ham  Go until jurong point, crazy.. Available only ...
1   ham                      Ok lar... Joking wif u oni...
2  spam  Free entry in 2 a wkly comp to win FA Cup fina...
3   ham  U dun say so early hor... U c already then say...
4   ham  Nah I don't think he goes to usf, he lives aro...
label
ham     4825
spam     747
Name: count, dtype: int64


In [105]:
spam_df = df[df['label']=='spam']
ham_df  = df[df['label']=='ham']

spam_sample = spam_df.sample(50, random_state=42)
ham_sample  = ham_df.sample(50, random_state=42)

df = pd.concat([spam_sample, ham_sample])
df = df.sample(frac=1, random_state=42).reset_index(drop=True)

print(df['label'].value_counts())


label
ham     50
spam    50
Name: count, dtype: int64


In [106]:
df['label'] = df['label'].map({'ham':0, 'spam':1})

In [107]:
df.head()

,label,text
0,0,What * u wearing?
1,0,Can you call me plz. Your number shows out of ...
2,0,Another month. I need chocolate weed and alcohol.
3,1,"UpgrdCentre Orange customer, you may now claim..."
4,1,Bloomberg -Message center +447797706009 Why wa...


cleaning text

In [108]:
stop_words = set(stopwords.words('english'))

def clean_text(text):
    text = text.lower()
    text = re.sub(r'[^a-z\s]', '', text)
    words = text.split()
    words = [w for w in words if w not in stop_words]
    return " ".join(words)

df['clean_text'] = df['text'].apply(clean_text)


In [109]:
from nltk.corpus import stopwords
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [110]:
X_train, X_test, y_train, y_test = train_test_split(
    df['clean_text'],
    df['label'],
    test_size=0.2,
    stratify=df['label'],
    random_state=42
)

In [111]:
vectorizer = TfidfVectorizer(
    max_features=3000,
    ngram_range=(1,2)
)

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)


In [112]:
model = MultinomialNB(alpha=0.5)
model.fit(X_train_vec, y_train)


MultinomialNB(alpha=0.5)

In [113]:
y_pred = model.predict(X_test_vec)

print("ACCURACY:", accuracy_score(y_test, y_pred))
print("\nCLASSIFICATION REPORT:\n")
print(classification_report(y_test, y_pred))

ACCURACY: 1.0

CLASSIFICATION REPORT:

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        10
           1       1.00      1.00      1.00        10

    accuracy                           1.00        20
   macro avg       1.00      1.00      1.00        20
weighted avg       1.00      1.00      1.00        20



In [114]:
cm = confusion_matrix(y_test, y_pred)
print("Confusion Matrix:\n", cm)


Confusion Matrix:
 [[10  0]
 [ 0 10]]


## test new email

In [115]:
def predict_email(text):
    text = clean_text(text)
    vec = vectorizer.transform([text])
    pred = model.predict(vec)[0]

    if pred == 1:
        print("SPAM ❌")
    else:
        print("HAM ✅")

# test examples
predict_email("Congratulations! You won a free iPhone")
predict_email("Hi, are we meeting tomorrow?")


SPAM ❌
HAM ✅
