# Python-дағы ОББ, ерекше жағдайларды өңдеу (try-except), модульдер мен пакеттер, NumPy кіріспе (массивтер, векторизация, негізгі операциялар)

1. Мақсат                                                                        
Python тілінде объектілі-бағытталған бағдарламалау (ОББ), ерекше жағдайларды өңдеу (try-except), модульдер мен пакеттермен жұмыс, сондай-ақ NumPy кітапханасындағы негізгі операцияларды меңгеру.

# Есеп 1.1:

---
Кітап (Kitap) атты класс құрыңыз. Бұл кластың атауы (atau) және авторы (avtory) деген екі атрибуты болуы керек.\
__init__ әдісін қолданып, кітап атауын және авторын инициализациялаңыз.\
Класс ішінде кітап_туралы_мәлімет (kitap_turaly_malimet) атты әдіс жасаңыз. Бұл әдіс "Кітап: [Атауы], Авторы: [Авторы]" деген мәтінді консольға шығаруы керек.\
Осы класстан бір нысан (объект) жасаңыз және кітап_туралы_мәлімет әдісін шақырыңыз.

In [3]:
class Kitaptar:
  def __init__(self, atau, avtory):
    self.atau=atau
    self.avtory=avtory

  def kitap_turaly_malimet(self):
    print(f'Kitap: {self.atau}, Avtory: {self.avtory}')

In [4]:
kitap=Kitaptar('Harry Potter', 'J. K. Rowling')

kitap.kitap_turaly_malimet()

Kitap: Harry Potter, Avtory: J. K. Rowling


# Есеп 2.1:

---

numpy кітапханасын np ретінде импорттаңыз.\
1-ден 9-ға дейінгі (9-ды қоса алғанда) сандардан тұратын бір өлшемді NumPy массивін (arr_a) жасаңыз.\
3x3 өлшемді (3 жол, 3 баған) сандардан тұратын екі өлшемді NumPy массивін (arr_b) жасаңыз. Мысалы, 1-ден 9-ға дейінгі сандарды пайдаланыңыз.\
Әр массивтің өлшемін (.shape) және деректер түрін (.dtype) шығарыңыз.

In [5]:
import numpy as np

In [8]:
arr_a=np.arange(1,10)
arr_a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
arr_a.shape

(9,)

In [11]:
arr_a.dtype

dtype('int64')

In [12]:
arr_b=arr_a.reshape(3,3)
arr_b

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
arr_b.shape

(3, 3)

In [14]:
arr_b.dtype

dtype('int64')

# Есеп 3.1:


---

numpy-ді np ретінде импорттаңыз.\
Кездейсоқ 5 бүтін саннан тұратын екі бір өлшемді NumPy массивін (vec1 және vec2) жасаңыз (мысалы, 1-ден 10-ға дейінгі).\
Векторизацияны қолдана отырып (циклсіз):
- Екі массивті қосыңыз (vec1 + vec2).
- Әрбір элементтің квадратын есептеңіз (vec1 ** 2).
vec1 массивінің орташа мәнін (.mean()) және ең үлкен мәнін (.max()) табыңыз.\

Барлық нәтижелерді консольға шығарыңыз.

In [50]:
import numpy as np

In [60]:
vec1 = np.random.randint(1,10,5)
vec2=np.random.randint(1,10,5)

In [61]:
vec1

array([3, 7, 8, 1, 8])

In [62]:
vec2

array([9, 3, 4, 4, 7])

In [63]:
f'qosyndysy: {vec1+vec2}'

'qosyndysy: [12 10 12  5 15]'

In [64]:
f'kvadraty: {np.square(vec1)}'

'kvadraty: [ 9 49 64  1 64]'

In [65]:
f'oratasha mani(vec1): {np.mean(vec1)}'

'oratasha mani(vec1): 5.4'

In [66]:
orta=np.mean(vec2)
f'ortasha mani(vec2): { orta}'

'ortasha mani(vec2): 5.4'

In [67]:
f'en ulken mani (vec1): {np.max(vec1)}'

'en ulken mani (vec1): 8'

In [68]:
f'en ulken mani (vec2): {np.max(vec2)}'

'en ulken mani (vec2): 9'